# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "src/Natasha.CSharp/Natasha.CSharp.Compiler"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[DEPENDENCY SRC]"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "System.Reflection.MetadataLoadContext"
      - dependency-name: "Microsoft.Extensions.DependencyModel"

  - package-ecosystem: "github-actions"
    directory: ".github"
    schedule:
      interval: "monthly"
      time: "05:00"
      timezone: "Asia/Harbin"
    commit-message:
      prefix: "[DEPENDENCY ACTION]"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
      time: "05:00"
      timezone: "Asia/Harbin"
    commit-message:
      prefix: "[DEPENDENCY ACTION]"
    labels:
      - "dependencies"


